config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
  
  snippets:
    extraRelabelConfigs: |
      - source_labels: [__meta_kubernetes_pod_label_name]
        target_label: name
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - replacement: ${cluster_name}
        target_label: cluster

tolerations:
  - operator: Exists

serviceAccount:
  create: true
  name: promtail